services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: log-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sf http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\\|yellow\"'",
        ]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 40s
    networks:
      - lognet

  redis:
    image: redis:7-alpine
    container_name: log-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - lognet

  backend:
    build: ./backend
    container_name: log-backend
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTIC_URL=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    networks:
      - lognet

  frontend:
    build: ./frontend
    container_name: log-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - lognet

  worker:
    build: ./backend
    container_name: log-worker
    command: npm run worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_NAME=logQueue
      - ELASTIC_URL=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    networks:
      - lognet

volumes:
  es_data:

networks:
  lognet:
